### ISSUE TITLE
请问可以支持文件夹吗输入吗，感觉对于批处理来说会更加方便一点

### ISSUE THREAD

**Issue by Kenny-Ch** [nukemiko/takiyasha#1]
May you support folder input? I believe that it will be more convenient for batch processing.

**Comment by nukemiko** [comment]
近期将会发布新版本，支持处理文件夹（不包括子文件夹）里的文件。

**Comment by nukemiko** [comment]
新版本已经支持文件夹输入：https://github.com/nukemiko/takiyasha/releases/tag/v0.4.1

**Comment by Kenny-Ch** [comment]
> @Kenny-Ch 新版本已经支持文件夹输入：https://github.com/nukemiko/takiyasha/releases/tag/v0.4.1

好的！我尝试一下新版本，虽然之前已经通过.bat实现了批处理
